name: Update Guidelines

on:
  issues:
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up env.
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update guidelines file
      run: |
        python src/fetch_table_guidelines.py -f docs/guidelines_last.json
        ls -rtl docs/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit new guidelines file
      uses: devops-infra/action-commit-push@v1.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: "Update guidelines file"

#    - name: Commit new guidelines file
#      uses: EndBug/add-and-commit@v9.1.4
#      with:
#        author_name: argobot-hub
#        author_email: argobot84@gmail.com
#        message: "Update guidelines file"
#        add: "docs/guidelines_last.json --force"
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
